-- 1) A small warehouse is plenty for CSV + analytics
CREATE WAREHOUSE IF NOT EXISTS FINANCE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

-- 2) Project DB + schemas
CREATE DATABASE IF NOT EXISTS FINANCE;
CREATE SCHEMA IF NOT EXISTS FINANCE.RAW;
CREATE SCHEMA IF NOT EXISTS FINANCE.STG;
CREATE SCHEMA IF NOT EXISTS FINANCE.CURATED;
CREATE SCHEMA IF NOT EXISTS FINANCE.MART;

USE WAREHOUSE FINANCE_WH;

CREATE OR REPLACE FILE FORMAT FINANCE.RAW.FF_TSV
  TYPE = CSV
  FIELD_DELIMITER = '\t'
  PARSE_HEADER=TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE FILE FORMAT FINANCE.RAW.FF_CSV
  TYPE = CSV
  FIELD_DELIMITER = ','
  PARSE_HEADER=TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE FINANCE.RAW.STAGE_SPEND;

CREATE OR REPLACE TABLE FINANCE.RAW.DISCOVER_RAW
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION => '@FINANCE.RAW.STAGE_SPEND/discover/',
      FILE_FORMAT => 'FINANCE.RAW.FF_CSV'
    )
  )
);

CREATE OR REPLACE TABLE FINANCE.RAW.CHASE_RAW
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION => '@FINANCE.RAW.STAGE_SPEND/chase/',
      FILE_FORMAT => 'FINANCE.RAW.FF_CSV'
    )
  )
);
CREATE OR REPLACE FILE FORMAT FINANCE.RAW.FF_CAPONE_PREVIEW
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 0
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  TRIM_SPACE = TRUE
  EMPTY_FIELD_AS_NULL = TRUE;

SELECT
  METADATA$FILENAME AS file,
  $1 AS c1, $2 AS c2, $3 AS c3, $4 AS c4, $5 AS c5, $6 AS c6, $7 AS c7
FROM @STAGE_SPEND/capone/ (FILE_FORMAT => 'FINANCE.RAW.FF_CAPONE_PREVIEW');


CREATE OR REPLACE TABLE FINANCE.RAW.CAPONE_RAW
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION => '@FINANCE.RAW.STAGE_SPEND/capone/',
      FILE_FORMAT => 'FINANCE.RAW.FF_CSV'
    )
  )
);

CREATE OR REPLACE TABLE FINANCE.RAW.AMEX_RAW
USING TEMPLATE (
  SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
  FROM TABLE(
    INFER_SCHEMA(
      LOCATION => '@FINANCE.RAW.STAGE_SPEND/amex/',
      FILE_FORMAT => 'FINANCE.RAW.FF_CSV'
    )
  )
);

SHOW TABLES IN SCHEMA FINANCE.RAW;
DESCRIBE TABLE FINANCE.RAW.DISCOVER_RAW;
DESCRIBE TABLE FINANCE.RAW.CHASE_RAW;
DESCRIBE TABLE FINANCE.RAW.CAPONE_RAW;
DESCRIBE TABLE FINANCE.RAW.AMEX_RAW;

LIST @STAGE_SPEND/chase/;

COPY INTO FINANCE.RAW.AMEX_RAW
FROM @STAGE_SPEND/amex/
FILE_FORMAT = (FORMAT_NAME='FF_CSV')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO FINANCE.RAW.CHASE_RAW
FROM @STAGE_SPEND/chase/
FILE_FORMAT = (FORMAT_NAME='FF_CSV')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;
  
COPY INTO FINANCE.RAW.CAPONE_RAW
FROM @FINANCE.RAW.STAGE_SPEND/capone/
FILE_FORMAT = (FORMAT_NAME='FF_CSV')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO FINANCE.RAW.DISCOVER_RAW
FROM @STAGE_SPEND/discover/
FILE_FORMAT = (FORMAT_NAME='FF_CSV')
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

select * FROM FINANCE.RAW.CAPONE_RAW;

